version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: market_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password


