// proto/ohlc.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/ohlc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OHLCStreamer_StreamCandlesticks_FullMethodName = "/proto.OHLCStreamer/StreamCandlesticks"
)

// OHLCStreamerClient is the client API for OHLCStreamer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OHLCStreamerClient interface {
	StreamCandlesticks(ctx context.Context, in *CandlestickRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Candlestick], error)
}

type oHLCStreamerClient struct {
	cc grpc.ClientConnInterface
}

func NewOHLCStreamerClient(cc grpc.ClientConnInterface) OHLCStreamerClient {
	return &oHLCStreamerClient{cc}
}

func (c *oHLCStreamerClient) StreamCandlesticks(ctx context.Context, in *CandlestickRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Candlestick], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OHLCStreamer_ServiceDesc.Streams[0], OHLCStreamer_StreamCandlesticks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CandlestickRequest, Candlestick]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OHLCStreamer_StreamCandlesticksClient = grpc.ServerStreamingClient[Candlestick]

// OHLCStreamerServer is the server API for OHLCStreamer service.
// All implementations must embed UnimplementedOHLCStreamerServer
// for forward compatibility.
type OHLCStreamerServer interface {
	StreamCandlesticks(*CandlestickRequest, grpc.ServerStreamingServer[Candlestick]) error
	mustEmbedUnimplementedOHLCStreamerServer()
}

// UnimplementedOHLCStreamerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOHLCStreamerServer struct{}

func (UnimplementedOHLCStreamerServer) StreamCandlesticks(*CandlestickRequest, grpc.ServerStreamingServer[Candlestick]) error {
	return status.Errorf(codes.Unimplemented, "method StreamCandlesticks not implemented")
}
func (UnimplementedOHLCStreamerServer) mustEmbedUnimplementedOHLCStreamerServer() {}
func (UnimplementedOHLCStreamerServer) testEmbeddedByValue()                      {}

// UnsafeOHLCStreamerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OHLCStreamerServer will
// result in compilation errors.
type UnsafeOHLCStreamerServer interface {
	mustEmbedUnimplementedOHLCStreamerServer()
}

func RegisterOHLCStreamerServer(s grpc.ServiceRegistrar, srv OHLCStreamerServer) {
	// If the following call pancis, it indicates UnimplementedOHLCStreamerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OHLCStreamer_ServiceDesc, srv)
}

func _OHLCStreamer_StreamCandlesticks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CandlestickRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OHLCStreamerServer).StreamCandlesticks(m, &grpc.GenericServerStream[CandlestickRequest, Candlestick]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OHLCStreamer_StreamCandlesticksServer = grpc.ServerStreamingServer[Candlestick]

// OHLCStreamer_ServiceDesc is the grpc.ServiceDesc for OHLCStreamer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OHLCStreamer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.OHLCStreamer",
	HandlerType: (*OHLCStreamerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCandlesticks",
			Handler:       _OHLCStreamer_StreamCandlesticks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/ohlc.proto",
}
